### ISSUE TITLE
Support web3js contract API

### ISSUE THREAD

**Issue by MadelineMurray** [ConsenSys/web3js-eea#139]
As a user, I want to be able to interact with private contracts in the same way as public contracts when using web3js-eea. Where possible, I want web3js-eea to detect when a contract is private and just work.

webj3 doc - https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html

Some additional comments on the [original PR](https://github.com/hyperledger/besu/issues/504) before I moved it to this repo. 

18/09/2020 -> Requested in customer conversation.

**Comment by petermetz** [comment]
https://github.com/hyperledger/besu/issues/504#issuecomment-692270840
> hi @RafaelAPB - no one is working on this currently and this enhancement isn't on our short term roadmap. If you (or anyone else) wanted to contribute an implementation, we'd be happy to help you get started.

@MadelineMurray I'd be interested in submitting a PR and would love some help in terms of getting started, any pointers are much appreciated.
Context: I'm working on Cactus with Rafael.

**Comment by macfarla** [comment]
this repo has been deprecated in favour of web3js-quorum https://github.com/ConsenSys/web3js-quorum
