### ISSUE TITLE
Implement sending an unsigned transaction with web3js-eea

### ISSUE THREAD

**Issue by MadelineMurray** [ConsenSys/web3js-eea#140]
As a user I want to be able to able to use web3js-eea with EthSigner to sign transactions with my key stored in EthSigner.  That is, I want to submit unsigned transactions from web3js-eea to `eea_sendTransaction`. 

18/09/2020 -> Requested in customer conversation.

**Comment by macfarla** [comment]
This project is deprecated and replaced by web3js-quorum that offers wider compatibility with the Quorum stack including both Besu and GoQuorum. https://github.com/ConsenSys/web3js-quorum
