### ISSUE TITLE
Cannot import PrivateTransaction class to sign private transactions

### ISSUE THREAD

**Issue by aleBiriri** [ConsenSys/web3js-eea#146]
Hello,
I have used web3.js-eea very few times, so i'm sorry if this is a basic question.
I'm trying to sign a transaction in the client side, without immediately sending it to Blockchain,i.e i want to just sign the tx, and get the signedRlpEncoded string.
Looking at the code, i though i could create a private tx object, using PrivateTransaction and then call the serialize method, like this:

```
const tx = new PrivateTransaction()

//Set tx properties, like tx.to, tx.privateFor...

const signedRlpEncoded = tx.serialize().toString("hex");
```

The problem is that i cannot import or use the PrivateTransaction constructor in my code. I have tried with lines such as

```
const PrivateTransaction = require("web3-eea") // this is wrong because PrivateTransaction  = EEAClient constructor
import PrivateTransaction  from "web3-eea"  // does not work
import {PrivateTransaction} from "web3-eea" // does not work
```

So, how could i import this constructor to use it?

### Note
It is worth to mention that i changed the last line of the file node_modules/web3-eea/src/index.js from:

`module.exports = EEAClient;`

to 

`module.exports = {EEAClient:EEAClient,PrivateTransaction:PrivateTransaction};`

and then i could import the PrivateTransaction like this:

`import {PrivateTransaction} from "web3-eea" 
`

**Comment by MadelineMurray** [comment]
hi @aleBiriri - a lot of team members are out on leave this week so there's been a delay in getting this answered.  Thanks for your patience.

**Comment by aleBiriri** [comment]
Hello and Happy new year!!

Is there any advance on this?

Thank you very much in advance!

**Comment by pinges** [comment]
Comment from Akua:
It looks like the package isn’t currently set up to export PrivateTransaction. The changes that the user made to the module.exports will break existing uses of EEAClient (I’m guessing the tests would not pass in that case). I think it’s worth thinking about how people should be able to use the package and structuring the exported API accordingly.

I think it would be possible to do what the user wants without breaking the existing API, but the library would have to change to using ES6 modules and export/import syntax.

**Comment by aleBiriri** [comment]
Thank you for your reponse.

Is there any plan to update the library in order to use the PrivateTransaction class?

Thanks!

**Comment by macfarla** [comment]
Hi @aleBiriri - sorry it's been a bit quiet around here lately - this project has been deprecated and replaced by web3js-quorum that offers wider compatibility with the Quorum stack including both Besu and GoQuorum. https://github.com/ConsenSys/web3js-quorum
If you still have questions, feel free to raise them over there!
