### ISSUE TITLE
Update examples default dev chain ID to 1337 once value changed in Besu

### ISSUE THREAD

**Issue by NicolasMassart** [ConsenSys/web3js-eea#150]
Besu dev network default chain id is going to be updated in https://github.com/hyperledger/besu/issues/2121
Once done, it will require to also update examples in this repos.

See also doc related issue and https://github.com/hyperledger/besu-docs/issues/664

**Comment by macfarla** [comment]
integration tests failing, I think because quickstart docker is out of date
https://github.com/ConsenSys/quorum-dev-quickstart/pull/49/files

**Comment by vmichalik** [comment]
what's the latest on this @macfarla?
