### ISSUE TITLE
multiNodeExample: Error: Returned error: Method not enabled

### ISSUE THREAD

**Issue by mohjam2004** [ConsenSys/web3js-eea#164]
Hi,
I'm checking privacy on my deployed besu network based on this doc:
https://besu.hyperledger.org/en/21.1.6/Tutorials/Privacy/web3js-eea-Multinode-example/

but I get this error: 
![image](https://user-images.githubusercontent.com/59224403/121802046-c97fa300-cc4f-11eb-9cbc-e3cbcb66061a.png)

I have changed chain id in keys.js from 1337 to 2018(my chain id)
 in my privacy node web3 is enabled for rpc and ws 
![image](https://user-images.githubusercontent.com/59224403/121802056-d7352880-cc4f-11eb-96e3-0652380ed5b3.png)

what's wrong in my configuration?
![image](https://user-images.githubusercontent.com/59224403/121802063-e0be9080-cc4f-11eb-891f-8ba50855c370.png)

I have deployed my private network based on this:
https://github.com/ConsenSys/quorum-kubernetes/tree/master/kubectl/quorum-besu/ibft2-with-privacy
![image](https://user-images.githubusercontent.com/59224403/121802198-83770f00-cc50-11eb-9e22-450687479630.png)

**Comment by mohjam2004** [comment]
I have found the problem:
The rpc-http-api method PRIV was not set on  config.toml  of privacy nodes. Now I don't get the previous error: 
rpc-http-api=["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET", "EEA", "PRIV"]

My new issue is that the transaction is got stuck in mining
![image](https://user-images.githubusercontent.com/59224403/121803896-d0f77a00-cc58-11eb-859c-5b06e4f3593b.png)

**Comment by mohjam2004** [comment]
Hi again,
The second problem has been resolved.
I set min-gas-price=0 in config.toml of my besu nodes and I didn't get the error again.
![image](https://user-images.githubusercontent.com/59224403/121805180-4e25ed80-cc5f-11eb-9c80-831e7049fb61.png)

**Comment by macfarla** [comment]
Glad you solved the problem :)
