### ISSUE TITLE
Clean up onchain examples

### ISSUE THREAD

**Issue by MadelineMurray** [ConsenSys/web3js-eea#63]
Simplify the onchain examples to: 
1. Remove the transaction receipts 
2. Show group membership only for the group created in the example

**Comment by MadelineMurray** [comment]
Expanding this issue to cover: 
* Using priv_call instead of sending transactions to read contract values

**Comment by MadelineMurray** [comment]
Address for interoperable privacy

**Comment by macfarla** [comment]
This project is deprecated and replaced by web3js-quorum that offers wider compatibility with the Quorum stack including both Besu and GoQuorum. https://github.com/ConsenSys/web3js-quorum
