### ISSUE TITLE
Investigate blind auction failure 

### ISSUE THREAD

**Issue by MadelineMurray** [ConsenSys/web3js-eea#69]
Investigate blind auction failure

**Comment by MadelineMurray** [comment]
Madeline to add enough details that someone can actually work on this - PO fail.

**Comment by lucassaldanha** [comment]
@MadelineMurray if you don't add details in 3 days we'll close it!!!!!! :)

**Comment by macfarla** [comment]
This project is deprecated and replaced by web3js-quorum that offers wider compatibility with the Quorum stack including both Besu and GoQuorum. https://github.com/ConsenSys/web3js-quorum
