### ISSUE TITLE
Make error handling consistent for JSON-RPC requests

### ISSUE THREAD

**Issue by magooster** [ConsenSys/web3js-eea#74]
Some methods catch and re throw

return axios
      .post(host, payload)
      .then(result => {
        return result.data.result;
      })
      .catch(error => {
        if (error.response) {
          throw JSON.stringify(error.response.data);
        } else {
          throw error;
        }
      });

others do nothing

return axios.post(host, payload).then(result => {
      return result.data.result;
    });

Be nice if all methods were consistent in their handling...

**Comment by MadelineMurray** [comment]
Need to ensure we do this when updating for interoperable privacy.

**Comment by macfarla** [comment]
This project is deprecated and replaced by web3js-quorum that offers wider compatibility with the Quorum stack including both Besu and GoQuorum. https://github.com/ConsenSys/web3js-quorum
