### ISSUE TITLE
Add test and coverage reports to CircleCI build information

### ISSUE THREAD

**Issue by lucassaldanha** [ConsenSys/web3js-eea#79]
It would be good to update our CircleCI build with the testing and coverage reports. It seems to be easy to do so.

References:
• https://circleci.com/docs/2.0/configuration-reference/#store_test_results
• https://circleci.com/docs/2.0/collect-test-data/
• https://circleci.com/docs/2.0/code-coverage/#javascript

**Comment by MadelineMurray** [comment]
Includes investigation effort to identify approach

**Comment by MadelineMurray** [comment]
Talk to Yetis

**Comment by macfarla** [comment]
https://github.com/ConsenSys/web3js-eea/issues/167

**Comment by macfarla** [comment]
This project is deprecated.
