### ISSUE TITLE
Add tests to exercise error conditions for RPC methods

### ISSUE THREAD

**Issue by akuanti** [ConsenSys/web3js-eea#88]
In order to increase coverage of the main functions in the library, add tests that generate errors for the following functions:

- [ ] `eea.sendRawTransaction`
  - [ ] fail if both privacyGroupId and privateFor are set
  - [ ] error from RPC
- [ ] `priv.createPrivacyGroup`
- [ ] `priv.call`
- [ ] `priv.getTransaction`

**Comment by MadelineMurray** [comment]
Now that refactor has been done this is lower priority.

**Comment by MadelineMurray** [comment]
Address when updating library for interoperable privacy

**Comment by macfarla** [comment]
This project is deprecated and replaced by web3js-quorum that offers wider compatibility with the Quorum stack including both Besu and GoQuorum. https://github.com/ConsenSys/web3js-quorum
